### GET (Basic)
http://localhost:5000

### GET Tickets (ALL)
http://localhost:5000/api/tickets
https://wme-tickets-api-v2.herokuapp.com/api/tickets

### GET Comments (ALL)
http://localhost:5000/api/tickets/1/comments

### GET Tickets (by ID)
http://localhost:5000/api/tickets/13

### GET Comments (ID)
http://localhost:5000/api/tickets/2/comments/4

### POST (Tickets)
POST http://localhost:5000/api/tickets HTTP/1.1
content-type: application/json

{
  "title": "Crazy error message",
  "description": "Create a new comment test",
  "category_id": 1,
  "opened_by": 2,
  "comment": "Comment is attached to this ticket"
}

### POST (Comments)
POST http://localhost:5000/api/tickets/13/comments HTTP/1.1
content-type: application/json

{
  "description": "Create AWS account",
  "project_id": 13,
  "notes": "Go to https://aws.amazon.com and sign up for a 'Free Tier' account",
  "is_complete": false
}

### PUT (Tickets)
# PUT https://api-devdesk.herokuapp.com/api/tickets/1/ HTTP/1.1
PUT http://localhost:5000/api/tickets/1/ HTTP/1.1
content-type: application/json

{
 "assigned_to": 1
}

### PUT (Action)
PUT http://localhost:5000/api/tickets/12/comments/16 HTTP/1.1
content-type: application/json

{
  "description": "Kick off test project",
  "project_id": 12,
  "notes": "Let's get it started.",
  "is_complete": true
}

### DELETE (Tickets)
DELETE http://localhost:5000/api/tickets/5

### DELETE (Comments)
DELETE http://localhost:5000/api/tickets/5/comments/5